---
- name: Copy all needed certificates to target server({{ target.target_host }})
  include_tasks: copy_cert.yml
  loop_control:
    loop_var: cert_type
  with_items:
    - cert
    - chain
    - fullchain
    - privkey
  when: "domains[cert_type + '_path'] is defined"
