---
- name: Add the certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
  when: "ansible_distribution == 'Ubuntu'"

- name: Install dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - nginx-full
    - certbot
  when: ansible_pkg_mgr == "apt"
